var mongoose = require('mongoose');

var orderSchema = new mongoose.Schema({
  "user_id"          : {type: mongoose.Schema.Types.ObjectId, ref: 'user_info', index:true },
  "order_id"         : {type:String, index:true},
  "firstCurrency"    : {type:String, index:true},
  "secondCurrency"   : {type:String, index:true},
  "pair"             : {type:String, index:true},
  "Amount"           : Number,
  "filledAmount"     : {type:Number, default:0},
  "Price"            : {type:Number, index:true},
  "Type"             : {type:String, index:true},
  "Fee"              : {type:Number, default:0},
  "fee_per"          : {type:Number, default:0},
  "Total"            : Number,
  "status"           : String,
  "xid"              : {type:String, index:true},
  "prefer_xid"       : {type:String, default:"", index:true},
  "matchtime"        : {type:Date},
  "paytime"          : {type:Date},
  "sellertime"       : {type:Date},
  "confirmtime"      : {type:Date},
  "disputetime"      : {type:Date},
  "matchid"          : {type:mongoose.Schema.Types.ObjectId, ref:'p2p_coin_order', index:true },
  "partial_matchid"  : {type:mongoose.Schema.Types.ObjectId, ref:'p2p_coin_order', index:true },
  "dispute_match_id" : {type:mongoose.Schema.Types.ObjectId, ref:'p2p_dispute', index:true },
  "pagestatus"       : {type:String, default:"", index:true},
  "payremarks"       : {type:String, default:""},
  "dispute_status"   : {type:Number, default:0, index:true},
  "pay_status"       : {type:Number, default:0, index:true},
  "confirm_status"   : {type:Number, default:0, index:true},
  "match_status"     : {type:Number, default:0, index:true},
  "time_status"      : {type:Number, default:0, index:true},
  "cancel_status"    : {type:Number, default:0, index:true},
  "remain_status"    : {type:Number, default:0, index:true},
  "created_at"       : {type:Date, default:Date.now},
  "updated_at"       : {type:Date, default:Date.now}
}, {"versionKey" : false});
module.exports = mongoose.model('p2p_coin_order', orderSchema, 'p2p_coin_order')