const mongoose = require('mongoose');
const Schema = mongoose.Schema;
var ObjectIdSchema = Schema.ObjectId;
var ObjectId = mongoose.Types.ObjectId;

let usersSchema = new Schema({
  "username"     : String,
  "firstname"    : String,
  "lastname"     : String,
  "phone"        : String,
  "primary_value" : String,
  "protect_key"  : String,
  "dob"          : String,      
  "address"      : String,
  "country_code" : { type: String, default: '' },
  "alpha_code"   : { type: String, default: '' },
  "country"      : { type: String, default: '' },
  "state"        : String,
  "city"         : String,
  "zipcode"      : String,
  "gender"       : { type: String, default: '' },
  "added_val"    : String,
  "status"       : { type: Number, default: 0 },
  "profile_pic"  : { type: String, default: '' },
  "tfa_status"   : { type: Number, default: 0 },
  "tfa_code"     : String,
  "tfa_url"      : String,
  "kyc_status"   : { type: Number, default: 0 },
  "id_proof1"    : { type: String, default: '' },
  "id_proof"     : { type: String, default: '' },
  "id_reject"    : String,
  "id_status"    : { type: Number, default: 0 },
  "addr_proof"   : { type: String, default: '' },
  "addr_reject"  : String,
  "addr_status"  : { type: Number, default: 0 },
  "selfie_proof" : { type: String, default: '' },
  "selfie_reject": String,
  "selfie_status": { type: Number, default: 0 },
  "pro_status"   : { type: Number, default: 0 },
  "refer_id"     : String,
  "referrer_id"  : { type: String, default: '' },
  "xid"          : String,
  "bank_status"  : { type: Number, default: 0 },
  "forgot_code"  : String,  
  "created_at"   : { type: Date, default: Date.now },
  "updated_at"   : { type: Date, default: Date.now },
  "tfa_update"   : { type: Date, default: Date.now },
  "email"        : String,
  "user_fav"     : [],
  "secretkey"    : [],
  "otp_prefer"   : { type:String, default: '' },
  "ip_address"   : { type:String, default: '' },
  "email_otp"    : { type: String, default: '' },
  "with_pass"    : { type: String, default: '' },
  "applicant_id" : { type: String, default: '' },
  "api_key"      : { type: String, default: '' },
  "secret_key"   : { type: String, default: '' },
  "withdraw_otp" : String,
  "acc_type"     : String,
  "buss_address" : { type: String, default: '' },
  "reg_country"  : { type: String, default: '' },
  "legal"        : { type: String, default: '' },
  "wealth"       : { type: String, default: '' },
  "funds"        : { type: String, default: '' },
  "contact_name" : { type: String, default: '' },
}, {"versionKey" : false});

module.exports = mongoose.model('user_info', usersSchema, 'user_info');